version: 2

jobs:
  build:
    docker:
      - image: integratedexperts/ci-builder
        environment:
          GOSS_FILE_STRATEGY: cp
          DOCKER_VERSION: 18.09.2
    steps:
      - checkout
      - setup_remote_docker
      # nginx specifically requires a running php
      # container to run correctly.
      - run:
          name: Bring the containers up.
          command: docker-compose up -d
      - run:
          name: Install goss
          command: curl -fsSL https://goss.rocks/install | sh && goss --version
      - run:
          name: Build images
          command: tests/build.sh
      - run:
          name: Test images
          command: tests/run.sh
